import type { Metadata } from 'next';
import '@repo/ui/globals.css';
import Navbar from '@/components/Navbar';
import { Afacad_Flux } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const inter = Afacad_Flux({
  variable: '--font-inter',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${inter.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
